### ISSUE TITLE
Services_JSON is using deprecated PHP 4 style constructors

### ISSUE THREAD

**Issue by sjelfull** [SiftScience/sift-php#24]
I'm using the library under PHP 7.0, and i'm seeing this error message: **Methods with the same name as their class will not be constructors in a future version of PHP** (See [list of deprecated features](http://php.net/manual/en/migration70.deprecated.php))

**Comment by Lagg** [comment]
I can confirm this bug, and it's nothing short of hilarious that your simple commit hasn't been merged yet. Guess it's time for a mail.

**Comment by fredsadaghiani** [comment]
@Lagg @sjelfull My apologies. We'll get working on these right away. There was a miscommunication on our side about who would address these fixes. We'll get them resolved tonight (PST).

**Comment by yschatzberg** [comment]
@Lagg @sjelfull Thank you for finding and fixing this bug, and apologies for the delay on merging the PR.   We'd love to send you each a T-shirt if you're interested.  If you shoot me an email at yoav at siftscience dot com with your t-shirt size and an address to ship to we'll get them too you.
