### ISSUE TITLE
Autoloader errors

### ISSUE THREAD

**Issue by stevenbitner** [SiftScience/sift-php#32]
The `class_exists()` calls that wrap the PEAR functionality are not setting the autoload argument to false and thus will cause errors in applications that rely on autoloaders for their namespaces/classes. _lib/Services_JSON-1.0.3/JSON.php_ `class_exists()` should both include the second parameter set to false.

**Comment by lucacri** [comment]
+1 . This is breaking my app too

**Comment by quanpod** [comment]
@stevenbitner @lucacri Apologies for the slow response here - acknowledging the request.  We'll put this on the list, were you otherwise able to work around this?

**Comment by stevenbitner** [comment]
I have indeed addressed this and an issue with PHPUNIT in a fork.

**Comment by ehrmann** [comment]
Merged in #68
