### ISSUE TITLE
Undefined class constant 'VERSION' error

### ISSUE THREAD

**Issue by cmstactics** [SiftScience/sift-php#58]
In using this with composer on Ubuntu with PHP 7.1, I get this error:
PHP Fatal error:  Uncaught Error: Undefined class constant 'VERSION' in /var/www/.../html/vendor/siftscience/sift-php/lib/SiftRequest.php:73
In removing the constant from that line, it works.  Not sure if it is a compatibility issue or I'm not doing something properly.

**Comment by viaskal-sift** [comment]
Closing this issue as not reproducible one
