### ISSUE TITLE
Add a param proxy for Curl

### ISSUE THREAD

**Issue by ma3achou** [SiftScience/sift-php#63]
It's not an issue, it's a suggestion ... I can do it, but I prefere to ask you before ... and what do you think about it.

**Comment by ehrmann** [comment]
My first thought was adding a `$curlOpts` array to the `SiftClient` constructor, but it looks like libcurl (which PHP cURL uses) honors the `http_proxy` environment variable, so that might be the right approach.

**Comment by ehrmann** [comment]
@ma3achou We're looking into this change in #65 for connection pooling scenarios, but it would also work for simple http proxying.

**Comment by ehrmann** [comment]
Merged #65

**Comment by ma3achou** [comment]
Oh perfect ! :) ... Thanks !
