### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by radykal-com** [SiftScience/sift-php#76]
Hi,

We are getting the error `Array and string offset access syntax with curly braces is deprecated` when updating our application to PHP 7.4.

The curly braces syntax has been deprecated and only brackets `[]` are allowed from PHP 7.4

Is there any way to have the fix in latest and apply the patch for some older versions? Maybe replacing the JSON.php class with the builtin json from PHP is a better approach like merging the changes from https://github.com/SiftScience/sift-php/pull/74

**Comment by atlantismgmt** [comment]
Solve this problem guys !!

**Comment by viaskal-sift** [comment]
@atlantismgmt could you pls double check, the issue should have been resolved now

**Comment by radykal-com** [comment]
I can confirm it works fine now
