### ISSUE TITLE
Optional parameters not passed into getDecisions request

### ISSUE THREAD

**Issue by roman-getman** [SiftScience/sift-php#80]
The `getDecisions` method allows for optional parameters for filtering, but those are never passed on to the actual request.
The code in library version 4.0.0 is the following:
```
$request = new SiftRequest($url, SiftRequest::GET, $opts['timeout'],
                self::API3_VERSION,
                array('auth' => $this->api_key . ':'));
```
but it should probably look like this:
```
$request = new SiftRequest($url, SiftRequest::GET, $opts['timeout'],
                self::API3_VERSION,
                array('auth' => $this->api_key . ':', 'params' => $opts));
```

**Comment by viaskal-sift** [comment]
@roman-getman please, double check the latest version, the issue should be solved there
